import { useCallback, useEffect, useRef, useState } from "react"

const SWIPE_START_THRESHOLD = 8
const VERTICAL_CANCEL_THRESHOLD = 12
const COMMIT_THRESHOLD = 72
const MAX_VALID_TRANSLATE = 96
const INVALID_RESISTANCE = 0.25
const MAX_INVALID_TRANSLATE = 16

type GestureMode = "undecided" | "horizontal" | "vertical"

interface DragVisual {
  translateX: number
  revealSide: "left" | "right" | null
}

const REST: DragVisual = { translateX: 0, revealSide: null }

/** The row's displayed translation + which reveal (if any) is showing, for
 * a given raw pointer deltaX and the creator's CURRENT favorite state.
 * Valid direction (add: right when not-favorited; remove: left when
 * favorited) clamps at ±96px and reveals its own side. Invalid direction
 * gets ×0.25 resistance capped at ±16px and shows no reveal — it can never
 * commit an action (spec sections 10-16). */
function computeDragVisual(deltaX: number, isFavorite: boolean): DragVisual {
  if (!isFavorite) {
    if (deltaX > 0) return { translateX: Math.min(deltaX, MAX_VALID_TRANSLATE), revealSide: "left" }
    return { translateX: Math.max(deltaX * INVALID_RESISTANCE, -MAX_INVALID_TRANSLATE), revealSide: null }
  }
  if (deltaX < 0) return { translateX: Math.max(deltaX, -MAX_VALID_TRANSLATE), revealSide: "right" }
  return { translateX: Math.min(deltaX * INVALID_RESISTANCE, MAX_INVALID_TRANSLATE), revealSide: null }
}

export interface UseSwipeToFavoriteResult {
  /** Current displayed translateX in px — 0 at rest. */
  translateX: number
  /** Which reveal is showing behind the row, or null (rest / invalid direction). */
  revealSide: "left" | "right" | null
  /** 0.65 below the commit threshold, 1 at/above it — only meaningful while revealSide is non-null. */
  revealOpacity: number
  /** True right after release/cancel, so the row's own CSS can apply the
   * 180ms snap-back transition; false while actively dragging (spec:
   * "Do not add a transition while the pointer is actively dragging"). */
  isSnapping: boolean
  rowHandlers: {
    onPointerDown: (event: React.PointerEvent<HTMLElement>) => void
    onPointerMove: (event: React.PointerEvent<HTMLElement>) => void
    onPointerUp: (event: React.PointerEvent<HTMLElement>) => void
    onPointerCancel: (event: React.PointerEvent<HTMLElement>) => void
  }
  /** Wraps a click handler so the single click generated by a completed
   * swipe gesture (successful, failed-threshold, invalid-direction, or
   * cancelled) is skipped exactly once — every click before/after keeps
   * working normally (spec section 29). */
  guardClick: <T extends unknown[]>(handler: (...args: T) => void) => (...args: T) => void
}

/** Horizontal swipe/drag-to-favorite gesture for one creator row (spec's
 * "SWIPE TO FAVORITE / UNFAVORITE"). Pure Pointer Events — the same
 * implementation works for mouse/touch/pen, no gesture library. Kept out of
 * CreatorStatusList's own render so the threshold/resistance/vertical-scroll
 * arbitration math is independently unit-testable, and so each row's
 * gesture state (this hook is called once per row) can't leak into another
 * row's. `onCommit` fires on release only when the drag crossed the ±72px
 * threshold in the creator's own valid direction — never while still
 * dragging, and never for a cancelled/vertical/invalid-direction gesture. */
export function useSwipeToFavorite(isFavorite: boolean, onCommit: () => void): UseSwipeToFavoriteResult {
  const [visual, setVisual] = useState<DragVisual>(REST)
  const [isSnapping, setIsSnapping] = useState(false)

  const activePointerId = useRef<number | null>(null)
  const startX = useRef(0)
  const startY = useRef(0)
  const gestureMode = useRef<GestureMode>("undecided")
  const lastDeltaX = useRef(0)
  const justSwiped = useRef(false)

  // Read via refs inside the stable callbacks below instead of depending on
  // the latest `isFavorite`/`onCommit` props, so onPointerDown/Move/Up/Cancel
  // never need to be re-created (and re-bound) on every render. Synced in an
  // effect rather than during render itself (refs aren't render output).
  const isFavoriteRef = useRef(isFavorite)
  const onCommitRef = useRef(onCommit)
  useEffect(() => {
    isFavoriteRef.current = isFavorite
    onCommitRef.current = onCommit
  })

  const endGesture = useCallback((event: React.PointerEvent<HTMLElement>, commit: boolean) => {
    if (gestureMode.current === "horizontal") {
      justSwiped.current = true
      try {
        event.currentTarget.releasePointerCapture(event.pointerId)
      } catch {
        // Not captured, or unsupported in this environment (e.g. jsdom) — harmless.
      }
      if (commit) onCommitRef.current()
    }
    activePointerId.current = null
    gestureMode.current = "undecided"
    lastDeltaX.current = 0
    setIsSnapping(true)
    setVisual(REST)
  }, [])

  const onPointerDown = useCallback((event: React.PointerEvent<HTMLElement>) => {
    if (activePointerId.current !== null) return // spec: only one active pointer per row
    // A gesture that produced no click (typical for touch pans) must not
    // leave the guard armed and swallow the next genuine tap.
    justSwiped.current = false
    activePointerId.current = event.pointerId
    startX.current = event.clientX
    startY.current = event.clientY
    gestureMode.current = "undecided"
    lastDeltaX.current = 0
    // A new gesture starts clean even if the previous one's snap-back
    // transition was still animating.
    setIsSnapping(false)
    setVisual(REST)
  }, [])

  const onPointerMove = useCallback((event: React.PointerEvent<HTMLElement>) => {
    if (activePointerId.current !== event.pointerId) return
    const deltaX = event.clientX - startX.current
    const deltaY = event.clientY - startY.current

    if (gestureMode.current === "undecided") {
      if (Math.abs(deltaY) > VERTICAL_CANCEL_THRESHOLD && Math.abs(deltaY) > Math.abs(deltaX)) {
        // Hand this pointer back to native vertical scrolling entirely —
        // this row stops tracking it (spec section 8).
        gestureMode.current = "vertical"
        activePointerId.current = null
        return
      }
      if (Math.abs(deltaX) < SWIPE_START_THRESHOLD) return
      gestureMode.current = "horizontal"
      try {
        event.currentTarget.setPointerCapture(event.pointerId)
      } catch {
        // Unsupported in this environment (e.g. jsdom) — harmless; the
        // gesture still works via ordinary bubbling pointermove events.
      }
      // Prevent mouse-drag text selection now that this is a swipe, not a click.
      event.preventDefault()
    }

    if (gestureMode.current !== "horizontal") return
    lastDeltaX.current = deltaX
    setVisual(computeDragVisual(deltaX, isFavoriteRef.current))
  }, [])

  const onPointerUp = useCallback(
    (event: React.PointerEvent<HTMLElement>) => {
      if (activePointerId.current !== event.pointerId) return
      const commit = isFavoriteRef.current ? lastDeltaX.current <= -COMMIT_THRESHOLD : lastDeltaX.current >= COMMIT_THRESHOLD
      endGesture(event, commit)
    },
    [endGesture],
  )

  const onPointerCancel = useCallback(
    (event: React.PointerEvent<HTMLElement>) => {
      if (activePointerId.current !== event.pointerId) return
      endGesture(event, false)
    },
    [endGesture],
  )

  const guardClick = useCallback(<T extends unknown[]>(handler: (...args: T) => void) => {
    return (...args: T) => {
      if (justSwiped.current) {
        justSwiped.current = false
        return
      }
      handler(...args)
    }
  }, [])

  return {
    translateX: visual.translateX,
    revealSide: visual.revealSide,
    revealOpacity: Math.abs(visual.translateX) >= COMMIT_THRESHOLD ? 1 : 0.65,
    isSnapping,
    rowHandlers: { onPointerDown, onPointerMove, onPointerUp, onPointerCancel },
    guardClick,
  }
}
